In [1]:
import pandas as pd

In [ ]:
# Series - 1D array

In [2]:
age = pd.Series([21, 45])

In [3]:
print(age)

0    21
1    45
dtype: int64

In [4]:
print(age[0])

21

In [5]:
age = pd.Series(
    [21, 34],
    index = ["Alice", "Bob"]
)

In [7]:
print(age["Alice"])

21

In [9]:
# Data Frame - 2D labeled DS

In [19]:
data = {
    "Name": ["Alice", "Bob"],
    "Age": [21, 23],
    "Major": ["CS", None]
}

In [20]:
df = pd.DataFrame(data)

In [21]:
df

    Name  Age Major
0  Alice   21    CS
1    Bob   23  None

In [25]:
df.isna().sum()

Name     0
Age      0
Major    1
dtype: int64

In [28]:
df["Major"] = df["Major"].fillna("Unknown")

In [29]:
df

    Name  Age    Major
0  Alice   21       CS
1    Bob   23  Unknown

In [30]:
import numpy as np

arr = np.array([
    [20, 85],
    [25, 90],
    [30, 95]
])

In [31]:
arr

array([[20, 85],
       [25, 90],
       [30, 95]])

In [32]:
df = pd.DataFrame(
    arr,
    columns=["Age", "Score"],
    index=["Student1", "Student2", "Student3"]
)

In [33]:
df

          Age  Score
Student1   20     85
Student2   25     90
Student3   30     95

In [35]:
df_text = pd.read_table("/Users/jesanahammed/Desktop/DS/Class 1/ice_cream.txt", delimiter = ",")

In [36]:
df_text

         Date      Flavor  Scoops_Sold
0  2023-06-01     Vanilla          100
1  2023-06-01   Chocolate          150
2  2023-06-01  Strawberry          120
3  2023-06-02     Vanilla          110
4  2023-06-02   Chocolate          130
5  2023-06-02  Strawberry          140

In [38]:
df_text.isna().sum()

Date           0
Flavor         0
Scoops_Sold    0
dtype: int64

In [39]:
df_json = pd.read_json("/Users/jesanahammed/Desktop/DS/Class 1/ice_cream.json")

In [40]:
df_json

        Date      Flavor  Scoops_Sold
0 2023-06-01     Vanilla          100
1 2023-06-01   Chocolate          150
2 2023-06-01  Strawberry          120
3 2023-06-02     Vanilla          110
4 2023-06-02   Chocolate          130
5 2023-06-02  Strawberry          140

In [41]:
df_json.columns

Index(['Date', 'Flavor', 'Scoops_Sold'], dtype='object')